### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by heyalbero** [theCapypara/steamdeck-decky-syncthing#11]
I tried to install version 0.1, but ''TypeError: Failed to fetch'' was showing, I downloaded 0.2.1, because I read another issue here, and now it has an infinite loadinghy
![download](https://github.com/theCapypara/steamdeck-decky-syncthing/assets/114608432/dbe44a22-6c61-45d8-b164-ee07301e36de)

**Comment by theCapypara** [comment]
Can you try reloading the plugin? This is a known issue that happens sometimes, I tried some things to fix it but haven't really found the cause yet.

**Comment by ThePerfectVale** [comment]
Hi! Same issue here. Reloading gives me this error:
"TypeError: plugin_exports.default is not a function"
"at PluginLoader.importReactPlugin (http://localhost:1337/frontend/chunk-BpFm7XFv.js:7067:56)"
"at async PluginLoader.importPlugin (http://localhost:1337/frontend/chunk-BpFm7XFv.js:7044:13)"

Reinstalling seems to fix the issue temporarily until I reboot. It is also unable to detect my Syncthing GTK, so I had to choose Syncthing.

I am on SteamOS 3.6.8, with Decky version v3.0.0-pre4. The plugin's version is 0.2.1-389a842.

**Comment by DoronLGN** [comment]
I'm having a similar issue with the test version, whose use was prompted by the issue with the stable version heyalbero had.

**Comment by theCapypara** [comment]
The plugin currently is only tested and supported on stable Decky and SteamOS.

**Comment by agentwolf88** [comment]
Still no fix?

**Comment by BryanJacobs** [comment]
For me on Bazzite, the infinite loading happens after every boot. But reloading the plugin once from Decky's settings always fixes it.

**Comment by BryanJacobs** [comment]
> @BryanJacobs Are you using Decky Loader 3?

v3.0.0, yes.

**Comment by theCapypara** [comment]
Then I guess this issue is still not resolved. As I said before I have no idea what causes this and would need help to fix it.

**Comment by agentwolf88** [comment]
With Holoiso and ChimeraOS it works fine but not with Bazzite. :( I need Bazzite!

**Comment by agentwolf88** [comment]
Is there a log file where we can see what happens?

**Comment by fsworld009** [comment]
You can find logs for plugins in `~/homebrew/logs/{plugin-id}`, for this plugin they are in `~/homebrew/logs/decky-syncthing/`

I'm seeing the same issue on Bazzite with decky loader v3.0.2-pre2, logs below:

watchlog.log

```
2024-10-15T15:01:12.441007868+08:00 INFO::started 0.2.0.
2024-10-15T15:01:12.455412456+08:00 ERROR::panicked: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to run systemctl command ('daemon-reload'): exit status: 1. Stderr: Failed to connect to bus: No such file or directory\n" }
```


last_panic.txt

```
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to run systemctl command ('daemon-reload'): exit status: 1. Stderr: Failed to connect to bus: No such file or directory\n" }
   0: decky_syncthing_watchdog::panic_util::register_panic_hook::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2029:9
      std::panicking::rust_panic_with_hook
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
   4: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   6: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   7: decky_syncthing_watchdog::main::{{closure}}
   8: tokio::runtime::scheduler::current_thread::Context::enter
   9: tokio::runtime::context::set_scheduler
  10: tokio::runtime::runtime::Runtime::block_on
  11: decky_syncthing_watchdog::main
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: std::rt::lang_start::{{closure}}
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  15: main
  16: __libc_start_call_main
  17: __libc_start_main_alias_1
  18: _start
```
Hope this helps.

Current workaround is to reload the plugin manually in decky loader menu, as previous post pointed out.

**Comment by theCapypara** [comment]
Hm, I'm not sure how to solve this. This is either a bug in Decky Loader or Gamescope, the Syncthing user socket should always be available. Maybe Decky loads too early. I guess I could try adding a retry logic.

**Comment by theCapypara** [comment]
The newest plugin update adds some resilience to errors, the plugin may load better under Bazzite now.
See this PR of the pending plugin update submission: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/727
(always looking for test reports there to get it released sooner :) )

**Comment by fsworld009** [comment]
Looks like the version bump PR in decky-plugin-database is failing to build, so I don't see the new version on decky loader yet.

**Comment by theCapypara** [comment]
Nobody in the Decky Loader team has processed this PR, I think it just timed out because of this. I reached out to confirm, but ultimatively I can not do anything if they don't process the PR.

**Comment by matm616** [comment]
I was able to fix this issue by uninstalling the plugin from decky loader, going into desktop mode and deleting all references to the plugin from ~/homebrew then finally reinstalling it

**Comment by creedda** [comment]
FYI seeing this issue now on SteamOS 3.7.0 where before had no issues.

**Comment by Jaxsown** [comment]
> FYI seeing this issue now on SteamOS 3.7.0 where before had no issues.

me too

**Comment by burnermanx** [comment]
3.7.5 (beta) too.

**Comment by cheatfreak47** [comment]
After some tinkering, I was able to resolve this locally on my Deck by:

1. Uninstalling the Plugin via Decky
2. Go into Desktop Mode and delete the decky-syncthing folders in `~/homebrew/data` and `~/homebrew/settings`
3. Switch to Game Mode and go to `Settings` -> `System` and make sure Developer Mode is Enabled.
4. Go to `Settings` -> `Developer` and disable `CEF Remote Debugging` [This will temporarily disable Decky. It will be reenabled later with no loss of configuration.]
5. Restart the Steam Deck. Go into Desktop Mode.
6. Open Syncthing-GTK and open the Web UI.
7. Change the port Syncthing uses for it's Web UI to anything else. I use 8384.
8. Shutdown Syncthing via Web GUI
9. Close Syncthing-GTK from Tray
10. Restart the Steam Deck.
11. Going to `Settings` -> `Developer` and re-enable `CEF Remote Debugging`.
12. Switch to Desktop Mode, and install Decky again.
13. Restart the Steam Deck.
14. Switch Decky Store to Testing channel.
15. Install current 0.2.3-b02cb1d version of the Syncthing plugin.
16. Open the plugin via the plugins menu and hope it doesn't hang anymore.
17. Restart the Steam Deck.
18. Set up Syncthing Plugin after reboot.

**Comment by creedda** [comment]
> After some tinkering, I was able to resolve this locally on my Deck by:
> 
>     1. Uninstalling the Plugin via Decky
> 
>     2. Go into Desktop Mode and delete the decky-syncthing folders in `~/homebrew/data` and `~/homebrew/settings`
> 
>     3. Switch to Game Mode and go to `Settings` -> `System` and enable Developer Mode.
> 
>     4. Go to `Settings` -> `Developer` and disable `CEF Remote Debugging` [This will temporarily disable Decky. It will be reenabled later with no loss of configuration.]
> 
>     5. Restart the Steam Deck. Go into Desktop Mode.
> 
>     6. Open Syncthing-GTK and open the Web UI.
> 
>     7. Change the port Syncthing uses for it's Web UI to anything else. I use 8384.
> 
>     8. Shutdown Syncthing via Web GUI
> 
>     9. Close Syncthing-GTK from Tray
> 
>     10. Restart the Steam Deck.
> 
>     11. Going to `Settings` -> `Developer` and re-enable `CEF Remote Debugging`.
> 
>     12. Switch to Desktop Mode, and install Decky again, choosing the first option to simply reinstall/update it **without** resetting configuration.
> 
>     13. Restart the Steam Deck.
> 
>     14. Switch Decky Store to Testing channel.
> 
>     15. Install current 0.2.3-b02cb1d version of the Syncthing plugin.
> 
>     16. Open the plugin via the plugins menu and hope it doesn't hang anymore.
> 
>     17. Restart the Steam Deck.
> 
>     18. Set up Syncthing Plugin after reboot.
> 
>     19. (Optional) Return Decky Store to Stable channel.
> 
>     20. (Optional) Go to `Settings` -> `System` and disable Developer mode.

This resolved my problem for me. Looking forward to the fix making its way to the standard store eventually...

**Comment by theCapypara** [comment]
In order for the plugin to be accepted to the store, it needs test reports and reviews.
Please consider posting some here:
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/805
